DROP TABLE IF EXISTS UserBenefit;
DROP TABLE IF EXISTS SubscriptionBenefit;
DROP TABLE IF EXISTS DietPlanMeal;
DROP TABLE IF EXISTS DietPlan;
DROP TABLE IF EXISTS SubscriptionPlan;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS GymClassBooking;
DROP TABLE IF EXISTS GymClass;
DROP TABLE IF EXISTS PTClient;
DROP TABLE IF EXISTS TrainerBooking;
DROP TABLE IF EXISTS WorkoutSessionSet;
DROP TABLE IF EXISTS WorkoutSession;
DROP TABLE IF EXISTS AlternativeMeal;
DROP TABLE IF EXISTS WorkoutExercise;
DROP TABLE IF EXISTS ProgressEntry;
DROP TABLE IF EXISTS MealLog;
DROP TABLE IF EXISTS Subscription;
DROP TABLE IF EXISTS WorkoutPlan;
DROP TABLE IF EXISTS Injury;
DROP TABLE IF EXISTS InjuryRestriction;
DROP TABLE IF EXISTS NutritionTip;
DROP TABLE IF EXISTS Trainer;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Exercise;

CREATE TABLE IF NOT EXISTS User (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  username VARCHAR(255) UNIQUE DEFAULT NULL,
  avatar LONGTEXT DEFAULT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'USER',
  subscriptionPlan VARCHAR(255) NOT NULL DEFAULT 'free',
  theme VARCHAR(20) NOT NULL DEFAULT 'dark',
  targetCalories INT DEFAULT 2400,
  targetProtein FLOAT DEFAULT 180,
  targetCarbs FLOAT DEFAULT 270,
  targetFat FLOAT DEFAULT 70,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SubscriptionPlan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  planId VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  price FLOAT NOT NULL,
  annualPrice FLOAT NOT NULL,
  description TEXT NOT NULL,
  icon VARCHAR(100) NOT NULL,
  accentColor VARCHAR(50) NOT NULL,
  glowColor VARCHAR(50) NOT NULL,
  borderColor VARCHAR(50) NOT NULL,
  bgGradient VARCHAR(255) NOT NULL,
  popular BOOLEAN DEFAULT FALSE,
  cta VARCHAR(255) DEFAULT 'Join Now',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Exercise (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  difficulty VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  instructions TEXT NOT NULL,
  muscleGroups VARCHAR(255) NOT NULL,
  imageUrl VARCHAR(255) DEFAULT NULL,
  videoUrl VARCHAR(255) DEFAULT NULL,
  equipment VARCHAR(255) DEFAULT 'bodyweight',
  defaultSets INT DEFAULT 3,
  defaultReps INT DEFAULT 10,
  defaultTimeSecs INT DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Trainer (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT UNIQUE DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  specialty VARCHAR(255) NOT NULL,
  specialtyIcon VARCHAR(100) NOT NULL DEFAULT 'faDumbbell',
  specialtyColor VARCHAR(30) NOT NULL DEFAULT 'var(--accent-cyan)',
  avatar VARCHAR(10) NOT NULL DEFAULT '🏋️',
  bio TEXT NOT NULL,
  certifications TEXT NOT NULL,
  tags TEXT NOT NULL,
  imageUrl VARCHAR(255) DEFAULT NULL,
  rating FLOAT NOT NULL DEFAULT 0,
  reviews INT NOT NULL DEFAULT 0,
  experience INT NOT NULL DEFAULT 0,
  pricePerSession FLOAT NOT NULL DEFAULT 50,
  sessionsCompleted INT NOT NULL DEFAULT 0,
  available BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS WorkoutPlan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  daysPerWeek INT NOT NULL DEFAULT 3,
  level VARCHAR(50) DEFAULT 'Intermediate',
  weeks INT DEFAULT 12,
  goal VARCHAR(100) DEFAULT 'Muscle & Strength',
  label VARCHAR(50) DEFAULT NULL,
  isActive BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WorkoutExercise (
  id INT AUTO_INCREMENT PRIMARY KEY,
  planId INT NOT NULL,
  exerciseId INT NOT NULL,
  sets INT NOT NULL DEFAULT 3,
  reps INT NOT NULL DEFAULT 10,
  restSecs INT NOT NULL DEFAULT 60,
  day INT NOT NULL DEFAULT 1,
  orderIndex INT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (planId) REFERENCES WorkoutPlan(id) ON DELETE CASCADE,
  FOREIGN KEY (exerciseId) REFERENCES Exercise(id)
);

CREATE TABLE IF NOT EXISTS ProgressEntry (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  weight FLOAT DEFAULT NULL,
  bodyFat FLOAT DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MealLog (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  mealType VARCHAR(255) NOT NULL,
  calories INT NOT NULL,
  protein FLOAT NOT NULL DEFAULT 0,
  carbs FLOAT NOT NULL DEFAULT 0,
  fat FLOAT NOT NULL DEFAULT 0,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Subscription (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL UNIQUE,
  plan VARCHAR(255) NOT NULL DEFAULT 'free',
  status VARCHAR(255) NOT NULL DEFAULT 'active',
  billingCycle VARCHAR(50) NOT NULL DEFAULT 'monthly',
  autoRenew BOOLEAN NOT NULL DEFAULT TRUE,
  maxVisits INT NOT NULL DEFAULT 0,
  usedVisits INT NOT NULL DEFAULT 0,
  startsAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiresAt DATETIME DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GymClass (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  trainerId INT DEFAULT NULL,
  scheduledAt DATETIME NOT NULL,
  durationMins INT NOT NULL DEFAULT 60,
  maxSpots INT NOT NULL DEFAULT 20,
  spotsBooked INT NOT NULL DEFAULT 0,
  color VARCHAR(30) NOT NULL DEFAULT 'var(--accent-cyan)',
  description TEXT DEFAULT NULL,
  requiredPlan VARCHAR(50) NOT NULL DEFAULT 'basic',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (trainerId) REFERENCES Trainer(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS GymClassBooking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  classId INT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'confirmed',
  bookedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_user_class (userId, classId),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (classId) REFERENCES GymClass(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TrainerBooking (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  trainerId INT NOT NULL,
  scheduledAt DATETIME NOT NULL,
  durationMins INT NOT NULL DEFAULT 60,
  status VARCHAR(50) NOT NULL DEFAULT 'pending', -- pending, confirmed, cancelled, completed
  paymentStatus VARCHAR(50) NOT NULL DEFAULT 'unpaid', -- unpaid, awaiting_payment, paid, refunded
  notes TEXT DEFAULT NULL,
  totalPrice FLOAT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (trainerId) REFERENCES Trainer(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Payment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  bookingType VARCHAR(50) NOT NULL DEFAULT 'trainer', -- 'trainer' | 'class' | 'subscription'
  userId INT NOT NULL,
  amount FLOAT NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  status VARCHAR(50) NOT NULL DEFAULT 'pending', -- pending, completed, failed, refunded
  method VARCHAR(50) DEFAULT NULL,  -- 'card', 'wallet', 'cash', etc.
  transactionRef VARCHAR(255) DEFAULT NULL,
  paidAt DATETIME DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AlternativeMeal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  injury VARCHAR(255) NOT NULL,
  icon VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  benefit TEXT NOT NULL,
  calories INT NOT NULL,
  protein FLOAT NOT NULL DEFAULT 0,
  carbs FLOAT NOT NULL DEFAULT 0,
  fat FLOAT NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS WorkoutSession (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  planId INT DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  durationSecs INT NOT NULL DEFAULT 0,
  caloriesBurned INT NOT NULL DEFAULT 0,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (planId) REFERENCES WorkoutPlan(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS WorkoutSessionSet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sessionId INT NOT NULL,
  exerciseId INT NOT NULL,
  setNumber INT NOT NULL,
  reps INT DEFAULT NULL,
  weight FLOAT DEFAULT NULL,
  timeSecs INT DEFAULT NULL,
  isCompleted BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sessionId) REFERENCES WorkoutSession(id) ON DELETE CASCADE,
  FOREIGN KEY (exerciseId) REFERENCES Exercise(id)
);

CREATE TABLE IF NOT EXISTS DietPlan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  planId VARCHAR(50) NOT NULL UNIQUE,
  label VARCHAR(100) NOT NULL,
  labelColor VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  goal VARCHAR(255) NOT NULL,
  goalIcon VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  calories INT NOT NULL,
  protein FLOAT NOT NULL,
  carbs FLOAT NOT NULL,
  fat FLOAT NOT NULL,
  accentColor VARCHAR(50) NOT NULL,
  gradientFrom VARCHAR(100) NOT NULL,
  gradientTo VARCHAR(100) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DietPlanMeal (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dietPlanId INT NOT NULL,
  time VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  foods TEXT NOT NULL,
  calories INT NOT NULL,
  protein FLOAT NOT NULL,
  carbs FLOAT NOT NULL,
  fat FLOAT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (dietPlanId) REFERENCES DietPlan(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SubscriptionBenefit (
  id INT AUTO_INCREMENT PRIMARY KEY,
  planId VARCHAR(50) NOT NULL,
  benefitText VARCHAR(255) NOT NULL,
  isIncluded BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UserBenefit (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  benefitId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  usedCount INT NOT NULL DEFAULT 0,
  maxCount INT NOT NULL DEFAULT 0,
  expiresAt DATETIME DEFAULT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
  FOREIGN KEY (benefitId) REFERENCES SubscriptionBenefit(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PTClient (
  id INT AUTO_INCREMENT PRIMARY KEY,
  trainerId INT NOT NULL,
  userId INT NOT NULL,
  goal VARCHAR(255) NOT NULL DEFAULT 'General Fitness',
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  startDate DATE NOT NULL,
  endDate DATE DEFAULT NULL,
  sessionsPerWeek INT NOT NULL DEFAULT 3,
  progressNotes TEXT DEFAULT NULL,
  nextCheckIn DATE DEFAULT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_trainer_client (trainerId, userId),
  FOREIGN KEY (trainerId) REFERENCES Trainer(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Injury (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  type VARCHAR(255) NOT NULL, -- e.g., 'Knee', 'Shoulder', 'Back'
  description TEXT DEFAULT NULL,
  severity VARCHAR(50) DEFAULT 'moderate', -- 'mild', 'moderate', 'severe'
  status VARCHAR(50) DEFAULT 'active', -- 'active', 'recovering', 'healed'
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS InjuryRestriction (
  id INT AUTO_INCREMENT PRIMARY KEY,
  injuryType VARCHAR(255) NOT NULL UNIQUE,
  avoidExercises TEXT NOT NULL, -- JSON array of strings
  tip TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS NutritionTip (
  id INT AUTO_INCREMENT PRIMARY KEY,
  icon VARCHAR(50) NOT NULL,
  color VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
